### ISSUE TITLE
Not pulling all of todays games

### ISSUE THREAD

**Issue by DillonMercz** [andrewderango/NHL-Game-Probabilities#8]
For some reason, it only pulled 2 games, when there are 11 games today. Is there an error?

**Comment by andrewderango** [comment]
Is this for the NHL or NBA model?

There are only 2 NHL games today. There's 10 NBA games, and when I run the program, the model accurately indicates that there's 10 games today.

**Comment by DillonMercz** [comment]
This is for NHL.

**Comment by DillonMercz** [comment]
<img width="873" alt="Screenshot 2024-01-13 at 11 05 24 AM" src="https://github.com/andrewderango/NHL-Game-Probabilities/assets/16828120/43651a0a-0d9c-402d-b5cd-d59bd8dd6226">

**Comment by DillonMercz** [comment]
Sorry, error in my code.
